<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Yoo Ri Hwang" />


<title>Portfolio1: MLM</title>

<script src="site_libs/header-attrs-2.14/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Portfolio</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Index</a>
</li>
<li>
  <a href="p01.html">Portfolio 1</a>
</li>
<li>
  <a href="p02.html">Portfolio 2</a>
</li>
<li>
  <a href="p03.html">Portfolio 3</a>
</li>
<li>
  <a href="p04.html">Portfolio 4</a>
</li>
<li>
  <a href="p05.html">Portfolio 5</a>
</li>
<li>
  <a href="p06.html">Portfolio 6</a>
</li>
<li>
  <a href="p07.html">Portfolio 7</a>
</li>
<li>
  <a href="p08.html">Portfolio 8</a>
</li>
<li>
  <a href="p09.html">Portfolio 9</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Portfolio1: MLM</h1>
<h4 class="author">Yoo Ri Hwang</h4>
<h4 class="date">1/15/2022</h4>

</div>


<div id="source" class="section level1">
<h1>Source</h1>
<p><a
href="https://stat.utexas.edu/images/SSC/documents/SoftwareTutorials/MultilevelModeling.pdf"
class="uri">https://stat.utexas.edu/images/SSC/documents/SoftwareTutorials/MultilevelModeling.pdf</a></p>
<p><a
href="https://cehs-research.github.io/eBook_multilevel/mlm-2-levels-pupil-popularity.html"
class="uri">https://cehs-research.github.io/eBook_multilevel/mlm-2-levels-pupil-popularity.html</a></p>
<p>I refer the code on these websites. I followed the general tutorials
instructed on these website.</p>
<p>However, I made some changes. (I do some extra analysis that was not
on the website etc. ) I also explained by myself.</p>
<div id="notification" class="section level3">
<h3>notification</h3>
<p>ICC calculated based on the null model.</p>
</div>
</div>
<div id="prepare" class="section level1">
<h1>Prepare</h1>
<div id="load-library" class="section level2">
<h2>load library</h2>
<pre class="r"><code>library(foreign)
library(tidyverse)
library(haven)    
library(furniture)    
#install.packages(&#39;furniture&#39;)
library(stargazer)    
library(texreg)   
#install.packages(&#39;texreg&#39;)
library(gridExtra)    
#install.packages(&#39;gridExtra&#39;)
library(psych)        
library(car)      
#install.packages(&#39;car&#39;)
library(nlme)
library(lme4)         
library(lmerTest)     
library(optimx)
#install.packages(&#39;optimx&#39;)
# oh my gosh this never ends. 

# packages &lt;- c(&#39;performance&#39;,&#39;interactions&#39;,&#39;HLMdiag&#39;,&#39;sjstats&#39;)
# 
# installed_packages &lt;- packages %in% rownames(installed.packages())
# if (any(installed_packages == FALSE)) {
#   install.packages(packages[!installed_packages])
# }


#devtools::install_github(&quot;goodekat/redres&quot;)

library(performance)  
library(interactions) 
library(HLMdiag)      
library(redres)       
library(sjstats)     
library(predict3d)</code></pre>
</div>
<div id="load-data" class="section level2">
<h2>load data</h2>
<pre class="r"><code>data_raw &lt;- haven::read_sav(&quot;https://github.com/MultiLevelAnalysis/Datasets-third-edition-Multilevel-book/raw/master/chapter%202/popularity/SPSS/popular2.sav&quot;)

summary(data_raw)</code></pre>
<pre><code>##      pupil           class            extrav            sex        
##  Min.   : 1.00   Min.   :  1.00   Min.   : 1.000   Min.   :0.0000  
##  1st Qu.: 6.00   1st Qu.: 25.00   1st Qu.: 4.000   1st Qu.:0.0000  
##  Median :11.00   Median : 51.00   Median : 5.000   Median :1.0000  
##  Mean   :10.65   Mean   : 50.37   Mean   : 5.215   Mean   :0.5055  
##  3rd Qu.:16.00   3rd Qu.: 76.00   3rd Qu.: 6.000   3rd Qu.:1.0000  
##  Max.   :26.00   Max.   :100.00   Max.   :10.000   Max.   :1.0000  
##       texp          popular         popteach         Zextrav       
##  Min.   : 2.00   Min.   :0.000   Min.   : 1.000   Min.   :-3.3390  
##  1st Qu.: 8.00   1st Qu.:4.100   1st Qu.: 4.000   1st Qu.:-0.9625  
##  Median :15.00   Median :5.100   Median : 5.000   Median :-0.1703  
##  Mean   :14.26   Mean   :5.076   Mean   : 5.061   Mean   : 0.0000  
##  3rd Qu.:20.00   3rd Qu.:6.000   3rd Qu.: 6.000   3rd Qu.: 0.6218  
##  Max.   :25.00   Max.   :9.500   Max.   :10.000   Max.   : 3.7905  
##       Zsex             Ztexp            Zpopular          Zpopteach       
##  Min.   :-1.0108   Min.   :-1.8717   Min.   :-3.67188   Min.   :-2.89165  
##  1st Qu.:-1.0108   1st Qu.:-0.9559   1st Qu.:-0.70628   1st Qu.:-0.75523  
##  Median : 0.9888   Median : 0.1125   Median : 0.01703   Median :-0.04308  
##  Mean   : 0.0000   Mean   : 0.0000   Mean   : 0.00000   Mean   : 0.00000  
##  3rd Qu.: 0.9888   3rd Qu.: 0.8756   3rd Qu.: 0.66802   3rd Qu.: 0.66906  
##  Max.   : 0.9888   Max.   : 1.6388   Max.   : 3.19962   Max.   : 3.51762  
##     Cextrav           Ctexp              Csex        
##  Min.   :-4.215   Min.   :-12.263   Min.   :-0.5000  
##  1st Qu.:-1.215   1st Qu.: -6.263   1st Qu.:-0.5000  
##  Median :-0.215   Median :  0.737   Median : 0.5000  
##  Mean   : 0.000   Mean   :  0.000   Mean   : 0.0055  
##  3rd Qu.: 0.785   3rd Qu.:  5.737   3rd Qu.: 0.5000  
##  Max.   : 4.785   Max.   : 10.737   Max.   : 0.5000</code></pre>
<p>data structure:</p>
<p>pupils are nested in the class. trying to predict popluarity of pupil
by pupil’s gender and extravert. Furthermore, teacher’s experience
(class-level variable) will be considered.</p>
<p>To sum up, we have</p>
<p>Level-1 IV: pupil gender (SEX): coded as boy=0, girl=1<br />
Pupil’s extroversion (extrav) : 10-point scale.</p>
<p>Level-2IV: teacher’s experience (texp)</p>
<p>subsetting the data</p>
<pre class="r"><code># we only take what we need

data_pop &lt;- data_raw %&gt;%
  dplyr::mutate(id = paste(class,pupil, sep = &quot;-&quot;) %&gt;% #creating uniqe ids for student 
                  factor()) %&gt;%
  dplyr::select(id,pupil:popteach)

tibble::glimpse(head(data_pop,10))</code></pre>
<pre><code>## Rows: 10
## Columns: 8
## $ id       &lt;fct&gt; 1-1, 1-2, 1-3, 1-4, 1-5, 1-6, 1-7, 1-8, 1-9, 1-10
## $ pupil    &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
## $ class    &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
## $ extrav   &lt;dbl&gt; 5, 7, 4, 3, 5, 4, 5, 4, 5, 5
## $ sex      &lt;dbl+lbl&gt; 1, 0, 1, 1, 1, 0, 0, 0, 0, 0
## $ texp     &lt;dbl&gt; 24, 24, 24, 24, 24, 24, 24, 24, 24, 24
## $ popular  &lt;dbl&gt; 6.3, 4.9, 5.3, 4.7, 6.0, 4.7, 5.9, 4.2, 5.2, 3.9
## $ popteach &lt;dbl&gt; 6, 5, 6, 5, 6, 5, 5, 5, 5, 3</code></pre>
<p>check our fancy data</p>
<pre class="r"><code>data_pop %&gt;%
  dplyr::select(extrav, sex, texp, popular) %&gt;%
  data.frame() %&gt;%
  stargazer::stargazer(header=F,type=&quot;text&quot;)</code></pre>
<pre><code>## 
## =============================================================
## Statistic   N    Mean  St. Dev.  Min  Pctl(25) Pctl(75)  Max 
## -------------------------------------------------------------
## extrav    2,000 5.215   1.262     1      4        6      10  
## sex       2,000 0.505   0.500     0      0        1       1  
## texp      2,000 14.263  6.552     2      8        20     25  
## popular   2,000 5.076   1.383   0.000  4.100    6.000   9.500
## -------------------------------------------------------------</code></pre>
</div>
<div id="simple-plots" class="section level2">
<h2>simple plots</h2>
<ol style="list-style-type: decimal">
<li>when we overlook nested structure</li>
</ol>
<pre class="r"><code>data_pop %&gt;%
  ggplot() +
  aes(x = extrav, y = popular)+ 
  geom_point()+
  stat_smooth(method=lm)</code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="p01_files/figure-html/unnamed-chunk-5-1.png" width="672" />
2. consider cluster (group)</p>
<p>just for curious, we pick first 9 class and see</p>
<pre class="r"><code>data_pop %&gt;%
  dplyr::filter(class&lt;=9)%&gt;%
  ggplot() +
  aes(x = extrav, y = popular)+ 
  geom_point()+
  stat_smooth(method=lm)+
  facet_wrap(~ class) </code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="p01_files/figure-html/unnamed-chunk-6-1.png" width="672" />
3.</p>
<pre class="r"><code>ggplot(data      = data_pop,
       aes(x     = extrav,
           y     = popular,
           col   = class,
           group = class)) + 
  geom_point(size     = 1,
             alpha    = .5,
             position = &quot;jitter&quot;) +
  theme_minimal() +
  theme(legend.position = &quot;none&quot;) +
     geom_smooth(method = lm,
              se     = FALSE,
              size   = .5, 
              alpha  = .8)+ # to add regression line
  labs(title    = &quot;Popularity vs. Extraversion&quot;)</code></pre>
<p><img src="p01_files/figure-html/unnamed-chunk-7-1.png" width="672" />
This code (for third graph) was adpated from “<a
href="https://www.rensvandeschoot.com/tutorials/lme4/"
class="uri">https://www.rensvandeschoot.com/tutorials/lme4/</a>”</p>
</div>
<div id="centering" class="section level2">
<h2>Centering</h2>
<p>In the tutorial website, the author did not do the centering and keep
analyzing. However, in most cases, it is not useful unless it has
certian theoritical reasons.</p>
<pre class="r"><code>#install.packages(&#39;misty&#39;)
library(misty)</code></pre>
<pre><code>## Warning: package &#39;misty&#39; was built under R version 4.1.3</code></pre>
<pre><code>## |-------------------------------------|
## | misty 0.4.5 (2022-04-29)            |
## | Miscellaneous Functions T. Yanagida |
## |-------------------------------------|</code></pre>
<pre class="r"><code>#center level-1 predictor at the grandmean
data_pop$cgm_extrav&lt;-misty::center(data_pop$extrav)
data_pop$cgm_sex&lt;-misty::center(data_pop$sex)
data_pop$cgm_texp&lt;-misty::center(data_pop$texp)

#center level-1 predictor at the clustermean
data_pop$cwc_extrav&lt;-misty::center(data_pop$extrav, type=&quot;CWC&quot;, cluster = data_pop$class)
data_pop$cwc_sex&lt;-misty::center(data_pop$sex, type=&quot;CWC&quot;, cluster = data_pop$class)</code></pre>
</div>
<div id="single-level-equation-regression" class="section level2">
<h2>Single-level equation (regression)</h2>
<p><span class="math display">\[POP_{ij} = \beta_{0} + \beta_{1}SEX_{ij}
+ \beta_{2}EXT_{ij}+e_{ij}\]</span> Random parameter: <span
class="math inline">\(var[e_{ij}]\)</span><br />
fixed: intercept, slopes.</p>
<p>I won’t check the interaction at this point. This single-level
regression is rediculous in that it ignore nonindependenc.</p>
<pre class="r"><code>pop_lm&lt;- lm(popular ~ sex + extrav, data = data_pop) 

summary(pop_lm)</code></pre>
<pre><code>## 
## Call:
## lm(formula = popular ~ sex + extrav, data = data_pop)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.2527 -0.6652 -0.0454  0.7422  3.0473 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  2.78954    0.10355   26.94   &lt;2e-16 ***
## sex          1.50508    0.04836   31.12   &lt;2e-16 ***
## extrav       0.29263    0.01916   15.28   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.077 on 1997 degrees of freedom
## Multiple R-squared:  0.3938, Adjusted R-squared:  0.3932 
## F-statistic: 648.6 on 2 and 1997 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div id="multilevel-analysis" class="section level1">
<h1>MULTILEVEL ANALYSIS</h1>
<div id="intercept-only-model-unconditional-model-a.k.a.-null-model"
class="section level2">
<h2>1. intercept-only model (unconditional model, a.k.a. null
model)</h2>
<p>level 1:<br />
<span class="math display">\[y_{ij} = \beta_{0j} + e_{ij}\]</span>
level2:<br />
<span class="math inline">\(\beta_{0j}\)</span> is the intercept, and
this can be expressed as:</p>
<p><span class="math display">\[ \beta_{0j} = \gamma_{00} +
u_{0j}\]</span> <span class="math inline">\(\gamma_{00}\)</span> =
(overall mean)<br />
<span class="math inline">\(u_{0j}\)</span> = class effect, the variance
of the mean for each class around the overall mean of DV (popular)
score.</p>
<p>Combined together : mixed model</p>
<p><span class="math display">\[y_{ij} = \gamma_{00} + u_{0j} +
e_{ij}\]</span> random effect: var[<span
class="math inline">\(e_{ij}\)</span>], var[<span
class="math inline">\(u_{0j}\)</span>] fixed effect: <span
class="math inline">\(\gamma_{00}\)</span></p>
<pre class="r"><code>#My preference towards REML :D

null&lt;-lmer(popular~1 + (1|class), data=data_pop, REML=TRUE)
summary(null)</code></pre>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: popular ~ 1 + (1 | class)
##    Data: data_pop
## 
## REML criterion at convergence: 6330.5
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.5655 -0.6975  0.0020  0.6758  3.3175 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  class    (Intercept) 0.7021   0.8379  
##  Residual             1.2218   1.1053  
## Number of obs: 2000, groups:  class, 100
## 
## Fixed effects:
##             Estimate Std. Error       df t value Pr(&gt;|t|)    
## (Intercept)  5.07786    0.08739 98.90973    58.1   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Interpretaion: grandmean of pop of all students = 5.0779 class
average tends to vary by 0.08738 (approximately)</p>
<p>ICC : proportion of between-class variance and total variance.</p>
<p><span class="math display">\[\rho =
\frac{\sigma^{2}_{u0}}{\sigma^{2}_{u0} + \sigma^{2}_{e}}\]</span></p>
<p>By hand… <span class="math display">\[\rho = \frac{0.7021}{0.7021 +
1.2218}\]</span></p>
<p>or..using a great package..</p>
<pre class="r"><code>performance::icc(null)</code></pre>
<pre><code>## # Intraclass Correlation Coefficient
## 
##      Adjusted ICC: 0.365
##   Conditional ICC: 0.365</code></pre>
<p>interpretation: 36.5% of variance is due to the group</p>
</div>
<div id="one-level-1-predictor-fixed" class="section level2">
<h2>2. one level-1 predictor (fixed)</h2>
<p>level 1:<br />
<span class="math display">\[y_{ij} = \beta_{0j} + \beta_{1j}Extra_{ij}
+ e_{ij}\]</span> level2:</p>
<p>level2: <span class="math display">\[ \beta_{0j} = \gamma_{00} +
u_{0j}\]</span></p>
<p><span class="math display">\[ \beta_{1j} = \gamma_{00}\]</span> we do
not have a error term since this is fixed.</p>
<p>Combined together : mixed model</p>
<p><span class="math display">\[y_{ij} = \gamma_{00} +
\gamma_{10}Extra_{ij} + u_{0j} + e_{ij}\]</span> random effect:
var[<span class="math inline">\(e_{ij}\)</span>], var[<span
class="math inline">\(u_{0j}\)</span>]<br />
fixed effect: <span class="math inline">\(\gamma_{00}\)</span>, <span
class="math inline">\(\gamma_{10}\)</span></p>
<pre class="r"><code>#My preference towards REML :D

onefix&lt;-lmer(popular~1 + cgm_extrav + (1|class), data=data_pop, REML=TRUE)
summary(onefix)</code></pre>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: popular ~ 1 + cgm_extrav + (1 | class)
##    Data: data_pop
## 
## REML criterion at convergence: 5832.6
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.0644 -0.7267  0.0165  0.7088  3.3587 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  class    (Intercept) 0.8406   0.9168  
##  Residual             0.9304   0.9646  
## Number of obs: 2000, groups:  class, 100
## 
## Fixed effects:
##              Estimate Std. Error        df t value Pr(&gt;|t|)    
## (Intercept) 5.078e+00  9.421e-02 9.830e+01   53.90   &lt;2e-16 ***
## cgm_extrav  4.863e-01  2.015e-02 1.965e+03   24.13   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##            (Intr)
## cgm_extrav 0.000</code></pre>
</div>
<div id="one-level-1-predictor-random" class="section level2">
<h2>3. one level-1 predictor (random)</h2>
<p>level 1:<br />
<span class="math display">\[y_{ij} = \beta_{0j} + \beta_{1j}Extra_{ij}
+ e_{ij}\]</span> level2:</p>
<p>level2: <span class="math display">\[ \beta_{0j} = \gamma_{00} +
u_{0j}\]</span></p>
<p><span class="math display">\[ \beta_{1j} = \gamma_{10} +
u_{1j}\]</span></p>
<p>Combined together : mixed model</p>
<p><span class="math display">\[y_{ij} = \gamma_{00} +
\gamma_{10}Extra_{ij} + u_{0j} + u_{1j}Extrav_{ij} + e_{ij}\]</span></p>
<p>random effect: var[<span class="math inline">\(e_{ij}\)</span>],
var[<span class="math inline">\(u_{0j}\)</span>]<br />
fixed effect: <span class="math inline">\(\gamma_{00}\)</span>, <span
class="math inline">\(\gamma_{10}\)</span></p>
<pre class="r"><code>#My preference towards REML :D

oneram&lt;-lmer(popular~1 + cgm_extrav + (1 + cgm_extrav|class), data=data_pop, REML=TRUE)
summary(oneram)</code></pre>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: popular ~ 1 + cgm_extrav + (1 + cgm_extrav | class)
##    Data: data_pop
## 
## REML criterion at convergence: 5779.4
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.1961 -0.7291  0.0146  0.6816  3.2217 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev. Corr 
##  class    (Intercept) 0.89178  0.9443        
##           cgm_extrav  0.02599  0.1612   -0.88
##  Residual             0.89492  0.9460        
## Number of obs: 2000, groups:  class, 100
## 
## Fixed effects:
##             Estimate Std. Error       df t value Pr(&gt;|t|)    
## (Intercept)  5.03127    0.09702 97.07723   51.86   &lt;2e-16 ***
## cgm_extrav   0.49286    0.02546 89.69832   19.36   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##            (Intr)
## cgm_extrav -0.552</code></pre>
</div>
<div id="two-level-1-predictor-random" class="section level2">
<h2>4. two level-1 predictor (random)</h2>
<p>level 1:<br />
<span class="math display">\[y_{ij} = \beta_{0j} + \beta_{1j}EXTRA_{ij}
+ \beta_{1j}SEX_{ij} + e_{ij}\]</span> level2:</p>
<p>level2: <span class="math display">\[ \beta_{0j} = \gamma_{00} +
u_{0j}\]</span></p>
<p><span class="math display">\[ \beta_{1j} = \gamma_{10} +
u_{1j}\]</span> <span class="math display">\[ \beta_{2j} = \gamma_{20} +
u_{2j}\]</span></p>
<p>Combined together : mixed model</p>
<p><span class="math display">\[y_{ij} = \gamma_{00} +
\gamma_{10}Extra_{ij} + \gamma_{20}SEX_{ij} + u_{0j} + u_{1j}Extrav_{ij}
+ u_{2j}SEX_{ij} + e_{ij}\]</span></p>
<pre class="r"><code>tworam&lt;-lmer(popular~1 + cgm_extrav + cgm_sex + (1 + cgm_extrav+cgm_sex|class), data=data_pop)</code></pre>
<pre><code>## Warning in checkConv(attr(opt, &quot;derivs&quot;), opt$par, ctrl = control$checkConv, :
## Model failed to converge with max|grad| = 0.00263437 (tol = 0.002, component 1)</code></pre>
<pre class="r"><code>summary(tworam)</code></pre>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: popular ~ 1 + cgm_extrav + cgm_sex + (1 + cgm_extrav + cgm_sex |  
##     class)
##    Data: data_pop
## 
## REML criterion at convergence: 4870.5
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -3.01902 -0.64955 -0.01056  0.67100  3.11760 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev. Corr       
##  class    (Intercept) 0.673421 0.82062             
##           cgm_extrav  0.029849 0.17277  -0.74      
##           cgm_sex     0.005363 0.07324  -0.65 -0.04
##  Residual             0.552886 0.74356             
## Number of obs: 2000, groups:  class, 100
## 
## Fixed effects:
##              Estimate Std. Error        df t value Pr(&gt;|t|)    
## (Intercept)   5.02735    0.08408  95.88747   59.80   &lt;2e-16 ***
## cgm_extrav    0.44300    0.02343  91.03168   18.91   &lt;2e-16 ***
## cgm_sex       1.24483    0.03728 504.19278   33.39   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##            (Intr) cgm_xt
## cgm_extrav -0.533       
## cgm_sex    -0.125 -0.065
## optimizer (nloptwrap) convergence code: 0 (OK)
## Model failed to converge with max|grad| = 0.00263437 (tol = 0.002, component 1)</code></pre>
<p>model failed (convergency problem) with a random effect with a
variance very close to zero, this model should be reconsidered :
convergency</p>
<p>Alternatively, using ML:</p>
<pre class="r"><code>tworam&lt;-lmer(popular~1 + cgm_extrav + cgm_sex + (1 + cgm_extrav+cgm_sex|class), data=data_pop, REML=FALSE)</code></pre>
<pre><code>## boundary (singular) fit: see help(&#39;isSingular&#39;)</code></pre>
<pre class="r"><code>summary(tworam)</code></pre>
<pre><code>## Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite&#39;s
##   method [lmerModLmerTest]
## Formula: popular ~ 1 + cgm_extrav + cgm_sex + (1 + cgm_extrav + cgm_sex |  
##     class)
##    Data: data_pop
## 
##      AIC      BIC   logLik deviance df.resid 
##   4876.6   4932.6  -2428.3   4856.6     1990 
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -3.02040 -0.64844 -0.01135  0.66882  3.11852 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev. Corr       
##  class    (Intercept) 0.665942 0.81605             
##           cgm_extrav  0.029206 0.17090  -0.74      
##           cgm_sex     0.005292 0.07275  -0.65 -0.03
##  Residual             0.552663 0.74341             
## Number of obs: 2000, groups:  class, 100
## 
## Fixed effects:
##              Estimate Std. Error        df t value Pr(&gt;|t|)    
## (Intercept)   5.02763    0.08362  96.87007   60.12   &lt;2e-16 ***
## cgm_extrav    0.44293    0.02328  91.76423   19.02   &lt;2e-16 ***
## cgm_sex       1.24483    0.03726 511.51608   33.41   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##            (Intr) cgm_xt
## cgm_extrav -0.534       
## cgm_sex    -0.125 -0.064
## optimizer (nloptwrap) convergence code: 0 (OK)
## boundary (singular) fit: see help(&#39;isSingular&#39;)</code></pre>
<pre class="r"><code>isSingular(tworam, tol = 1e-4)</code></pre>
<pre><code>## [1] TRUE</code></pre>
<p>matrix argument is singular.</p>
</div>
<div id="one-level-2-predictor-and-two-level-1-predictor-wo-interaction"
class="section level2">
<h2>5. one level-2 predictor and two level-1 predictor (w/o
interaction)</h2>
<p>level 1:<br />
<span class="math display">\[y_{ij} = \beta_{0j} + \beta_{1j}EXTRA_{ij}
+ \beta_{2j}SEX_{ij} + e_{ij}\]</span></p>
<p>level2: <span class="math display">\[ \beta_{0j} = \gamma_{00}
+\gamma_{01}Texp_{j} + u_{0j}\]</span></p>
<p><span class="math display">\[ \beta_{1j} = \gamma_{10} +
u_{1j}\]</span> <span class="math display">\[ \beta_{2j} = \gamma_{20} +
u_{2j}\]</span></p>
<p>Combined together : mixed model</p>
<p><span class="math display">\[y_{ij} = \gamma_{00}
+\gamma_{01}Texp_{j} + \gamma_{20}SEX_{ij} +  u_{1j}Extrav_{ij} +
u_{2j}SEX_{ij} + u_{0j}+e_{ij}\]</span></p>
<pre class="r"><code>#My preference towards REML :D
# 
inter&lt;-lmer(popular~1+cgm_extrav+cgm_sex+texp + (1+cgm_extrav+cgm_sex|class), data = data_pop)
summary(inter)</code></pre>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: popular ~ 1 + cgm_extrav + cgm_sex + texp + (1 + cgm_extrav +  
##     cgm_sex | class)
##    Data: data_pop
## 
## REML criterion at convergence: 4833.3
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.1642 -0.6554 -0.0246  0.6711  2.9570 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev. Corr       
##  class    (Intercept) 0.284302 0.53320             
##           cgm_extrav  0.034740 0.18639  -0.09      
##           cgm_sex     0.002404 0.04903  -0.98 -0.09
##  Residual             0.551436 0.74259             
## Number of obs: 2000, groups:  class, 100
## 
## Fixed effects:
##              Estimate Std. Error        df t value Pr(&gt;|t|)    
## (Intercept) 3.753e+00  1.365e-01 1.031e+02   27.49   &lt;2e-16 ***
## cgm_extrav  4.529e-01  2.465e-02 9.621e+01   18.38   &lt;2e-16 ***
## cgm_sex     1.251e+00  3.694e-02 9.860e+02   33.86   &lt;2e-16 ***
## texp        8.951e-02  8.618e-03 1.013e+02   10.39   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##            (Intr) cgm_xt cgm_sx
## cgm_extrav -0.105              
## cgm_sex    -0.015 -0.066       
## texp       -0.911  0.089 -0.039
## optimizer (nloptwrap) convergence code: 0 (OK)
## boundary (singular) fit: see help(&#39;isSingular&#39;)</code></pre>
</div>
<div
id="two-levle-1-predictor-two-level-1-predictior-with-cross-level-interaction"
class="section level2">
<h2>6. two levle-1 predictor, two level 1 predictior (with cross-level
interaction)</h2>
<p>level 1:<br />
<span class="math display">\[y_{ij} = \beta_{0j} + \beta_{1j}EXTRA_{ij}
+ \beta_{2j}SEX_{ij} + e_{ij}\]</span></p>
<p>level2: <span class="math display">\[ \beta_{0j} = \gamma_{00}
+\gamma_{01}Texp_{j} + u_{0j}\]</span></p>
<p><span class="math display">\[ \beta_{1j} = \gamma_{10}
+\gamma_{11}Texp_{j}+ u_{1j}\]</span> <span class="math display">\[
\beta_{2j} = \gamma_{20} +\gamma_{21}Texp_{j}+ u_{2j}\]</span></p>
<p>Combined together : mixed model</p>
<p><span class="math display">\[y_{ij} = \gamma_{00}
+\gamma_{01}Texp_{j} + \gamma_{10}Extra_{ij} + \gamma_{20}SEX_{ij} +
\gamma_{11}Texp_{j}*Extrav_{ij} + \gamma_{21}Texp_{j}*Sex_{ij} +
u_{1j}*Extrav_{ij} + u_{2j}SEX_{ij} + u_{0j}+e_{ij}\]</span></p>
<pre class="r"><code>#My preference towards REML :D
# 
inter&lt;-lmer(popular~1+cgm_extrav+cgm_sex+cgm_texp + cgm_extrav*cgm_texp+cgm_sex*cgm_texp+ (1+cgm_extrav+cgm_sex|class), data = data_pop)</code></pre>
<pre><code>## boundary (singular) fit: see help(&#39;isSingular&#39;)</code></pre>
<pre class="r"><code>summary(inter)</code></pre>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: popular ~ 1 + cgm_extrav + cgm_sex + cgm_texp + cgm_extrav *  
##     cgm_texp + cgm_sex * cgm_texp + (1 + cgm_extrav + cgm_sex |      class)
##    Data: data_pop
## 
## REML criterion at convergence: 4786.7
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -3.12085 -0.64851 -0.01954  0.68699  3.05066 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev. Corr       
##  class    (Intercept) 0.286486 0.53524             
##           cgm_extrav  0.005583 0.07472  -0.10      
##           cgm_sex     0.004141 0.06435  -0.85 -0.45
##  Residual             0.552080 0.74302             
## Number of obs: 2000, groups:  class, 100
## 
## Fixed effects:
##                       Estimate Std. Error         df t value Pr(&gt;|t|)    
## (Intercept)           4.998284   0.056689  99.920415  88.170  &lt; 2e-16 ***
## cgm_extrav            0.450533   0.017465  82.663266  25.797  &lt; 2e-16 ***
## cgm_sex               1.240359   0.036858 571.596862  33.652  &lt; 2e-16 ***
## cgm_texp              0.097161   0.008700 103.199839  11.168  &lt; 2e-16 ***
## cgm_extrav:cgm_texp  -0.024704   0.002574  71.874116  -9.597 1.66e-14 ***
## cgm_sex:cgm_texp     -0.001772   0.005924 616.426402  -0.299    0.765    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) cgm_xt cgm_sx cgm_tx cgm_x:_
## cgm_extrav  -0.038                             
## cgm_sex     -0.137 -0.113                      
## cgm_texp    -0.021  0.120 -0.038               
## cgm_xtrv:c_  0.121  0.015  0.032 -0.120        
## cgm_sx:cgm_ -0.041  0.030 -0.015 -0.141 -0.142 
## optimizer (nloptwrap) convergence code: 0 (OK)
## boundary (singular) fit: see help(&#39;isSingular&#39;)</code></pre>
<pre class="r"><code>isSingular(inter, tol = 1e-4)</code></pre>
<pre><code>## [1] TRUE</code></pre>
<pre class="r"><code># the matrix argument is singular. </code></pre>
<p>If i did not center level 2 variable, it is like this.</p>
<pre class="r"><code>inter&lt;-lmer(popular~1+cgm_extrav+cgm_sex+texp + cgm_extrav*texp+cgm_sex*texp+ (1+cgm_extrav+cgm_sex|class), data = data_pop)</code></pre>
<pre><code>## Warning in checkConv(attr(opt, &quot;derivs&quot;), opt$par, ctrl = control$checkConv, :
## Model failed to converge with max|grad| = 0.00242626 (tol = 0.002, component 1)</code></pre>
<pre class="r"><code>summary(inter)</code></pre>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: popular ~ 1 + cgm_extrav + cgm_sex + texp + cgm_extrav * texp +  
##     cgm_sex * texp + (1 + cgm_extrav + cgm_sex | class)
##    Data: data_pop
## 
## REML criterion at convergence: 4786.7
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -3.12086 -0.64855 -0.01958  0.68701  3.05061 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev. Corr       
##  class    (Intercept) 0.286421 0.53518             
##           cgm_extrav  0.005583 0.07472  -0.09      
##           cgm_sex     0.004148 0.06441  -0.85 -0.45
##  Residual             0.552086 0.74302             
## Number of obs: 2000, groups:  class, 100
## 
## Fixed effects:
##                   Estimate Std. Error         df t value Pr(&gt;|t|)    
## (Intercept)       3.612478   0.137491 104.605988  26.274  &lt; 2e-16 ***
## cgm_extrav        0.802884   0.040418  71.830803  19.864  &lt; 2e-16 ***
## cgm_sex           1.265650   0.092683 666.043417  13.656  &lt; 2e-16 ***
## texp              0.097161   0.008699 103.230989  11.169  &lt; 2e-16 ***
## cgm_extrav:texp  -0.024704   0.002574  71.870503  -9.597 1.66e-14 ***
## cgm_sex:texp     -0.001773   0.005924 615.663046  -0.299    0.765    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) cgm_xt cgm_sx texp   cgm_x:
## cgm_extrav  -0.197                            
## cgm_sex     -0.110 -0.161                     
## texp        -0.911  0.161  0.114              
## cgm_xtrv:tx  0.158 -0.902  0.142 -0.120       
## cgm_sex:txp  0.111  0.142 -0.918 -0.142 -0.142
## optimizer (nloptwrap) convergence code: 0 (OK)
## Model failed to converge with max|grad| = 0.00242626 (tol = 0.002, component 1)</code></pre>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
