<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Yoo Ri Hwang" />


<title>APIM (portfolio 2)</title>

<script src="site_libs/header-attrs-2.14/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Portfolio</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Index</a>
</li>
<li>
  <a href="p01.html">Portfolio 1</a>
</li>
<li>
  <a href="p02.html">Portfolio 2</a>
</li>
<li>
  <a href="p03.html">Portfolio 3</a>
</li>
<li>
  <a href="p04.html">Portfolio 4</a>
</li>
<li>
  <a href="p05.html">Portfolio 5</a>
</li>
<li>
  <a href="p06.html">Portfolio 6</a>
</li>
<li>
  <a href="p07.html">Portfolio 7</a>
</li>
<li>
  <a href="p08.html">Portfolio 8</a>
</li>
<li>
  <a href="p09.html">Portfolio 9</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">APIM (portfolio 2)</h1>
<h4 class="author">Yoo Ri Hwang</h4>
<h4 class="date">unknown</h4>

</div>


<div id="source" class="section level1">
<h1>Source:</h1>
<p>I used the data and follow the general tutorial of this website:</p>
<p><a
href="https://quantdev.ssri.psu.edu/tutorials/actor-partner-interdependence-model-apim-basic-dyadicbivariate-analysis"
class="uri">https://quantdev.ssri.psu.edu/tutorials/actor-partner-interdependence-model-apim-basic-dyadicbivariate-analysis</a></p>
<p>and these following referneces:</p>
<p><a
href="https://bigdata.duke.edu/projects/actor-partner-interdependence-model-r-mental-and-physical-health-spouses"
class="uri">https://bigdata.duke.edu/projects/actor-partner-interdependence-model-r-mental-and-physical-health-spouses</a></p>
<p><a href="https://rdrr.io/github/RandiLGarcia/dyadr/man/apim.html"
class="uri">https://rdrr.io/github/RandiLGarcia/dyadr/man/apim.html</a></p>
<p><a
href="https://randilgarcia.github.io/week-dyad-workshop/Distinguishable.html#distingushable_dyads"
class="uri">https://randilgarcia.github.io/week-dyad-workshop/Distinguishable.html#distingushable_dyads</a></p>
<p>However, I try to explain by myself and make changes.</p>
</div>
<div id="overview" class="section level1">
<h1>Overview</h1>
<p>Actor Partner Interdependence Model (APIM)</p>
<p>APIM model for distinguishable dyads. (Two intercept approach)</p>
<div id="prepare-for-analysis" class="section level2">
<h2>Prepare for analysis</h2>
<p>packages</p>
<pre class="r"><code>library(ggplot2)   </code></pre>
<pre><code>## Warning: package &#39;ggplot2&#39; was built under R version 4.1.3</code></pre>
<pre class="r"><code>library(nlme)     
library(psych)     </code></pre>
<pre><code>## Warning: package &#39;psych&#39; was built under R version 4.1.3</code></pre>
<pre class="r"><code>library(reshape)   </code></pre>
<pre><code>## Warning: package &#39;reshape&#39; was built under R version 4.1.3</code></pre>
<pre class="r"><code>library(dplyr)</code></pre>
<pre><code>## Warning: package &#39;dplyr&#39; was built under R version 4.1.3</code></pre>
<p>data download</p>
<pre class="r"><code>filepath &lt;- &quot;https://quantdev.ssri.psu.edu/sites/qdev/files/wisc3raw_gender.csv&quot;
wisc4raw&lt;-read.csv(file=url(filepath), header=T)

data&lt;-wisc4raw[,c(&quot;id&quot;,&quot;verb1&quot;,&quot;verb6&quot;,&quot;perfo1&quot;,&quot;perfo6&quot;)]

print(head(data,10))</code></pre>
<pre><code>##    id verb1 verb6 perfo1 perfo6
## 1   1 24.42 55.64  19.84  44.19
## 2   2 12.44 37.81   5.90  40.38
## 3   3 32.43 50.18  27.64  77.72
## 4   4 22.69 44.72  33.16  61.66
## 5   5 28.23 70.95  27.64  64.22
## 6   6 16.06 39.94   8.45  39.08
## 7   7  8.50 40.83   4.85  41.03
## 8   8 14.11 25.68  18.72  42.36
## 9   9 15.52 45.52  13.37  38.53
## 10 10 20.07 48.65  15.26  48.39</code></pre>
<p>data reshaping</p>
<pre class="r"><code>data_long &lt;- reshape(data = data,
                    varying = c(&quot;verb1&quot;, &quot;verb6&quot;,
                                &quot;perfo1&quot;, &quot;perfo6&quot;),
                    timevar = c(&quot;grade&quot;), 
                    idvar = c(&quot;id&quot;),
                    direction = &quot;long&quot;, sep=&quot;&quot;)

print(head(data_long,10))</code></pre>
<pre><code>##      id grade  verb perfo
## 1.1   1     1 24.42 19.84
## 2.1   2     1 12.44  5.90
## 3.1   3     1 32.43 27.64
## 4.1   4     1 22.69 33.16
## 5.1   5     1 28.23 27.64
## 6.1   6     1 16.06  8.45
## 7.1   7     1  8.50  4.85
## 8.1   8     1 14.11 18.72
## 9.1   9     1 15.52 13.37
## 10.1 10     1 20.07 15.26</code></pre>
</div>
<div id="research-questions" class="section level2">
<h2>Research Questions</h2>
<p><em>Actor effect</em></p>
<ol style="list-style-type: decimal">
<li>verbal ability in the grade 1 can predict verbal ability in 6
grade?<br />
</li>
<li>performance ability in the garde 1 can predict performance ability
in 6 grade?</li>
</ol>
<p><em>Partner effect</em></p>
<ol start="3" style="list-style-type: decimal">
<li>verbal ability in the grade 1 can predict performance ability in 6
grade?<br />
</li>
<li>performance ability in the 1 grade can predict verbal abilit in 6
grade</li>
</ol>
</div>
<div id="basic-descript-stats-before-analysis" class="section level2">
<h2>Basic descript stats before analysis</h2>
<p>Basic stats</p>
<pre class="r"><code>describe(data$verb1)</code></pre>
<pre><code>##    vars   n  mean   sd median trimmed  mad  min   max range skew kurtosis   se
## X1    1 204 19.59 5.81  19.34    19.5 5.41 3.33 35.15 31.82 0.13    -0.05 0.41</code></pre>
<pre class="r"><code>describe(data$verb6)</code></pre>
<pre><code>##    vars   n  mean    sd median trimmed  mad   min   max range skew kurtosis
## X1    1 204 43.75 10.67  42.55   43.46 11.3 17.35 72.59 55.24 0.24    -0.36
##      se
## X1 0.75</code></pre>
<pre class="r"><code>describe(data$perfo1)</code></pre>
<pre><code>##    vars   n  mean   sd median trimmed mad min   max range skew kurtosis   se
## X1    1 204 17.98 8.35  17.66   17.69 8.3   0 46.58 46.58 0.35    -0.11 0.58</code></pre>
<pre class="r"><code>describe(data$perfo6)</code></pre>
<pre><code>##    vars   n  mean    sd median trimmed   mad   min   max range  skew kurtosis
## X1    1 204 50.93 12.48  51.76   51.07 13.27 10.26 89.01 78.75 -0.06     0.18
##      se
## X1 0.87</code></pre>
<p>Correlation</p>
<pre class="r"><code>cor(data[, 2:5])</code></pre>
<pre><code>##            verb1     verb6    perfo1    perfo6
## verb1  1.0000000 0.6541040 0.6101379 0.4779672
## verb6  0.6541040 1.0000000 0.6183155 0.6106694
## perfo1 0.6101379 0.6183155 1.0000000 0.6958321
## perfo6 0.4779672 0.6106694 0.6958321 1.0000000</code></pre>
<pre class="r"><code>pairs.panels(data[, c(&quot;verb1&quot;, &quot;verb6&quot;, &quot;perfo1&quot;, &quot;perfo6&quot;)])</code></pre>
<p><img src="p02_files/figure-html/unnamed-chunk-5-1.png" width="672" />
Visualization</p>
<pre class="r"><code>data_long %&gt;%
  subset(id &lt;=9) %&gt;%
  ggplot( aes( x= grade, group=id), legend = FALSE) +
  geom_point(aes(x=grade, y=verb), shape = 17, size= 3, color = &quot;blue&quot;) +
  geom_point(aes(x=grade, y=perfo), shape = 19, size= 3, color = &quot;green&quot;) +
  geom_line(aes(x=grade, y=verb), lty= 1, size=1, color = &quot;blue&quot;) +
  geom_line(aes(x=grade, y=perfo), lty= 1, size = 1, color=&quot;green&quot;) +
  xlab(&quot;grade&quot;) +
  ylab(&quot;verbal/performance ability&quot;) +
  ylim(0,80) + 
  scale_x_continuous(breaks= seq(0,7, by = 1)) +
  theme_classic () +
  facet_wrap( ~id)</code></pre>
<p><img src="p02_files/figure-html/unnamed-chunk-6-1.png" width="672" />
## Data prepare</p>
<pre class="r"><code>data_melt &lt;- reshape::melt(data=data,
                           id.vars=c(&quot;id&quot;,&quot;verb1&quot;,&quot;perfo1&quot;),
                           na.rm=F)

print(head(data_melt,10))</code></pre>
<pre><code>##    id verb1 perfo1 variable value
## 1   1 24.42  19.84    verb6 55.64
## 2   2 12.44   5.90    verb6 37.81
## 3   3 32.43  27.64    verb6 50.18
## 4   4 22.69  33.16    verb6 44.72
## 5   5 28.23  27.64    verb6 70.95
## 6   6 16.06   8.45    verb6 39.94
## 7   7  8.50   4.85    verb6 40.83
## 8   8 14.11  18.72    verb6 25.68
## 9   9 15.52  13.37    verb6 45.52
## 10 10 20.07  15.26    verb6 48.65</code></pre>
<pre class="r"><code>colnames(data_melt)[4:5]&lt;-c(&quot;grade6_variable&quot;,&quot;grade6_score&quot;)
data_melt&lt;-data_melt[order(data_melt$id, data_melt$grade6_variable),]
print(head(data_melt,10))</code></pre>
<pre><code>##     id verb1 perfo1 grade6_variable grade6_score
## 1    1 24.42  19.84           verb6        55.64
## 205  1 24.42  19.84          perfo6        44.19
## 2    2 12.44   5.90           verb6        37.81
## 206  2 12.44   5.90          perfo6        40.38
## 3    3 32.43  27.64           verb6        50.18
## 207  3 32.43  27.64          perfo6        77.72
## 4    4 22.69  33.16           verb6        44.72
## 208  4 22.69  33.16          perfo6        61.66
## 5    5 28.23  27.64           verb6        70.95
## 209  5 28.23  27.64          perfo6        64.22</code></pre>
<p>Creating dummy variable for further analysis</p>
<pre class="r"><code>data_melt$verb_on &lt;- ifelse(data_melt$grade6_variable == &quot;verb6&quot;, 1, 0)
data_melt$perform_on &lt;- ifelse(data_melt$grade6_variable == &quot;perfo6&quot;, 1, 0)
print(head(data_melt,10))</code></pre>
<pre><code>##     id verb1 perfo1 grade6_variable grade6_score verb_on perform_on
## 1    1 24.42  19.84           verb6        55.64       1          0
## 205  1 24.42  19.84          perfo6        44.19       0          1
## 2    2 12.44   5.90           verb6        37.81       1          0
## 206  2 12.44   5.90          perfo6        40.38       0          1
## 3    3 32.43  27.64           verb6        50.18       1          0
## 207  3 32.43  27.64          perfo6        77.72       0          1
## 4    4 22.69  33.16           verb6        44.72       1          0
## 208  4 22.69  33.16          perfo6        61.66       0          1
## 5    5 28.23  27.64           verb6        70.95       1          0
## 209  5 28.23  27.64          perfo6        64.22       0          1</code></pre>
</div>
<div id="apim-analysis" class="section level2">
<h2>APIM ANALYSIS</h2>
<p>The website’s explanation is not detailed enough for understand. Here
is some steps for undertanding this model.</p>
<ol style="list-style-type: decimal">
<li>DV= Grade 6 outcome.</li>
<li>We have both Verbal, and performance.</li>
</ol>
<div id="the-big-equation-for-two-intercept-approach"
class="section level3">
<h3>The big equation for two-intercept Approach</h3>
<p>** note ** The equation from the website and my equation from my head
has difference (# of residual)</p>
<ol start="3" style="list-style-type: decimal">
<li>the Equations are like:</li>
</ol>
<p>So when “verb_on” is equal to 0: <span class="math display">\[
Grade6outcome_{ij} = VerbOn_{ij}*(\beta_{v0} +
\beta_{v1}(Verb1)_{ij}+\beta_{v2}(Perform1)+e_{vj}) +
PerformOn_{ij}*(\beta_{p3}+\beta_{p4}(perform1)_{ij}+
\beta_{p5}(verb1)_{ij}+e_{vj})\]</span></p>
<p><strong>VerbOn=Dummy __ variable (Verb=1, not=0)</strong><br />
<strong>PerformOn=Dummy varaible (Perform=1, not=0)</strong></p>
</div>
<div id="performance" class="section level3">
<h3>Performance</h3>
<ol start="4" style="list-style-type: decimal">
<li>Thus, when verbOn = 0: <span class="math display">\[
Grade6outcome_{ij}
=  PerformOn_{ij}*(\beta_{p3}+\beta_{p4}(perform1)_{ij}+
\beta_{p5}(verb1)_{ij}+e_{pj})\]</span></li>
</ol>
<p><span class="math inline">\(\beta_{p3}\)</span> is Verbal’s intercept
<span class="math inline">\(\beta_{p4}\)</span> the actor effect on
perform <span class="math inline">\(\beta_{p5}\)</span> the partner
effect on perform <span class="math inline">\(e_{pj}\)</span> Perform’s
residual in person J</p>
</div>
<div id="verbal" class="section level3">
<h3>Verbal</h3>
<ol start="5" style="list-style-type: decimal">
<li>When the PerformOn is 0:</li>
</ol>
<p><span class="math display">\[ Grade6outcome_{ij} =
VerbOn_{ij}*(\beta_{v0} +
\beta_{v1}(Verb1)_{ij}+\beta_{v2}(Perform1)_{ij}+e_{vj}) \]</span> <span
class="math inline">\(\beta_{v0}\)</span> is Verbal’s intercept <span
class="math inline">\(\beta_{v1}\)</span> the actor effect on verbal
<span class="math inline">\(\beta_{v2}\)</span> the partner effect on
verbal <span class="math inline">\(e_{vj}\)</span> verb’s residual in
person J</p>
<pre class="r"><code>apim_full &lt;- gls(grade6_score ~   -1+   #no intercept 
                                 verb_on +      #verbal intercept
                                 verb_on:verb1 +  #verbal actor 
                                 verb_on:perfo1 + #performance  effect
                   
                                 perform_on + #performance intercept
                                 perform_on:perfo1 + #performance actor
                                 perform_on:verb1,  #verbal partner
               correlation = corSymm(form=~1|id),
               weights = varIdent(form=~1|verb_on), #allow for different error terms (error varianace ) for the two variables/or two members. in this case, V and P 
               data = data_melt,
               na.action = na.exclude)

# The reason why here use : rather than *
# &quot;Using * will force R to add the main effects, while : will only give you that specific interaction you’re asking for.&quot;
# Source: 
# https://randilgarcia.github.io/week-dyad-workshop/Distinguishable.html#distingushable_dyads

summary(apim_full)</code></pre>
<pre><code>## Generalized least squares fit by REML
##   Model: grade6_score ~ -1 + verb_on + verb_on:verb1 + verb_on:perfo1 +      perform_on + perform_on:perfo1 + perform_on:verb1 
##   Data: data_melt 
##        AIC      BIC    logLik
##   2879.029 2914.997 -1430.514
## 
## Correlation Structure: General
##  Formula: ~1 | id 
##  Parameter estimate(s):
##  Correlation: 
##   1    
## 2 0.312
## Variance function:
##  Structure: Different standard deviations per stratum
##  Formula: ~1 | verb_on 
##  Parameter estimates:
##        1        0 
## 1.000000 1.188537 
## 
## Coefficients:
##                       Value Std.Error   t-value p-value
## verb_on           19.869325 1.8634459 10.662679  0.0000
## perform_on        30.049124 2.2147736 13.567582  0.0000
## verb_on:verb1      0.809886 0.1150893  7.037017  0.0000
## verb_on:perfo1     0.446064 0.0800504  5.572292  0.0000
## perfo1:perform_on  0.962419 0.0951429 10.115507  0.0000
## verb1:perform_on   0.182846 0.1367879  1.336709  0.1821
## 
##  Correlation: 
##                   verb_n prfrm_ vrb_n:v1 vrb_n:p1 prf1:_
## perform_on         0.312                                
## verb_on:verb1     -0.738 -0.230                         
## verb_on:perfo1    -0.034 -0.011 -0.610                  
## perfo1:perform_on -0.011 -0.034 -0.190    0.312         
## verb1:perform_on  -0.230 -0.738  0.312   -0.190   -0.610
## 
## Standardized residuals:
##         Min          Q1         Med          Q3         Max 
## -2.55877996 -0.66034371 -0.02441614  0.62804539  3.69258907 
## 
## Residual standard error: 7.545255 
## Degrees of freedom: 408 total; 402 residual</code></pre>
</div>
<div id="results-interpretation" class="section level3">
<h3>Results interpretation</h3>
<p><strong>intercept</strong> :<br />
19.869325 : expected verbal score at grade 6 when grade 1 verb/perfo
scores are zero.<br />
30.049124 : expected perforamce score at grade 6 when grade 1 verb/perfo
scores are zero.</p>
<p><strong>verb_on:verb1 0.809886</strong><br />
1 point increase in verbal grade 1 is associated with 0.81 difference in
verbal 6<br />
<strong>verb_on:perfo1 0.446064</strong><br />
every 1 point increase in perfo grade 1 is assoicated with 0.45 diff in
verbal 6</p>
<p><strong>perfo1:perform_on 0.962419</strong><br />
1 point increase in performance grade 1 is associated with 0.96 diff in
perfo 6<br />
<strong>verb1:perform_on 0.182846 </strong><br />
non-sig.</p>
</div>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
