<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Yoo Ri Hwang" />


<title>Portfolio 7 : basic simulation</title>

<script src="site_libs/header-attrs-2.14/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Portfolio</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Index</a>
</li>
<li>
  <a href="p01.html">Portfolio 1</a>
</li>
<li>
  <a href="p02.html">Portfolio 2</a>
</li>
<li>
  <a href="p03.html">Portfolio 3</a>
</li>
<li>
  <a href="p04.html">Portfolio 4</a>
</li>
<li>
  <a href="p05.html">Portfolio 5</a>
</li>
<li>
  <a href="p06.html">Portfolio 6</a>
</li>
<li>
  <a href="p07.html">Portfolio 7</a>
</li>
<li>
  <a href="p08.html">Portfolio 8</a>
</li>
<li>
  <a href="p09.html">Portfolio 9</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Portfolio 7 : basic simulation</h1>
<h4 class="author">Yoo Ri Hwang</h4>
<h4 class="date">3/9/2022</h4>

</div>


<div id="overview" class="section level2">
<h2>Overview</h2>
<p>In this portfolio, I aim to be familiar with <em>basic</em>
simulation</p>
</div>
<div id="source-reference" class="section level2">
<h2>Source &amp; Reference</h2>
<ol style="list-style-type: decimal">
<li>Introducing Monte Carlo Methods with R (Robert &amp; Casella,
2010)</li>
<li><a
href="https://towardsdatascience.com/generate-simulated-dataset-for-linear-model-in-r-469a5e2f4c2e"
class="uri">https://towardsdatascience.com/generate-simulated-dataset-for-linear-model-in-r-469a5e2f4c2e</a><br />
<strong>3) <a
href="https://datascience4psych.github.io/DataScience4Psych/welcome-to-simulating-data.html"
class="uri">https://datascience4psych.github.io/DataScience4Psych/welcome-to-simulating-data.html</a></strong></li>
<li><a
href="https://cran.r-project.org/web/packages/holodeck/vignettes/simulating-data.html"
class="uri">https://cran.r-project.org/web/packages/holodeck/vignettes/simulating-data.html</a><br />
</li>
<li><a
href="https://blog.revolutionanalytics.com/2016/02/multivariate_data_with_r.html"
class="uri">https://blog.revolutionanalytics.com/2016/02/multivariate_data_with_r.html</a><br />
</li>
</ol>
<ol start="6" style="list-style-type: decimal">
<li><a
href="https://s3.amazonaws.com/assets.datacamp.com/production/course_6521/slides/chapter2.pdf"
class="uri">https://s3.amazonaws.com/assets.datacamp.com/production/course_6521/slides/chapter2.pdf</a></li>
</ol>
</div>
<div id="packages" class="section level2">
<h2>packages</h2>
<pre class="r"><code>library(ggfortify)
# install.packages(&#39;ggfortify&#39;)</code></pre>
</div>
<div id="univariate-normal-the-one-sample-t-test"
class="section level2">
<h2>Univariate Normal &amp; the one-sample t-test</h2>
<pre class="r"><code>x&lt;-rnorm(25, mean=0, sd=100)
# produce N(0.3, 20) sample of size 25. 
print(x)</code></pre>
<pre><code>##  [1]   78.5783919  -48.6760911   82.1872984 -193.3058837  -69.9214671
##  [6] -110.4420711 -182.1855311 -104.7357116   17.3502480   -0.7920323
## [11]  159.3186468  -46.5060275  251.1047941 -209.6525022  -21.8217907
## [16]  -17.5479677  -38.6764562   67.3345127 -190.8404457    9.5802376
## [21]  117.6044931   34.7087315  158.1322745  -34.7748120  -99.3102085</code></pre>
<pre class="r"><code>t.test(x) # one sample t-test to see if the true mean score would be 0 or not </code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  x
## t = -0.66377, df = 24, p-value = 0.5132
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  -64.64641  33.18326
## sample estimates:
## mean of x 
## -15.73157</code></pre>
<pre class="r"><code>#p-value: 0.99. </code></pre>
<p>Although I generate the x data to be mean of zero, Sd was
unrealistically high.</p>
<pre class="r"><code>y&lt;-rnorm(25, mean=0, sd=1)
# produce N(0.3, 20) sample of size 25. 
print(y)</code></pre>
<pre><code>##  [1]  0.79339127 -0.60543547 -2.19636480  1.78504693 -0.97087049  0.26128846
##  [7] -0.73638702  0.18798207  0.73815308  0.47690133  0.69829360 -1.06244633
## [13] -0.99415964 -0.43731534  2.14821281 -0.67841037  1.61931502 -0.39127677
## [19]  1.45184348  0.79156016 -0.10783755  0.31625290  0.07213807  0.17863253
## [25] -0.35497808</code></pre>
<pre class="r"><code>t.test(y) # one sample t-test to see if the true mean score would be 0 or not </code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  y
## t = 0.58859, df = 24, p-value = 0.5616
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  -0.2991323  0.5378147
## sample estimates:
## mean of x 
## 0.1193412</code></pre>
<pre class="r"><code>#p-value becomes much lower than t.test(x)</code></pre>
</div>
<div id="simple-regression" class="section level2">
<h2>Simple regression</h2>
<pre class="r"><code>set.seed(1)
x=seq(-3,3,le=5)
print(x)</code></pre>
<pre><code>## [1] -3.0 -1.5  0.0  1.5  3.0</code></pre>
<pre class="r"><code>y=2+4*x+rnorm(5)
lm(y~x)</code></pre>
<pre><code>## 
## Call:
## lm(formula = y ~ x)
## 
## Coefficients:
## (Intercept)            x  
##       2.129        4.222</code></pre>
<p><span class="math display">\[Y_{ij}=\alpha + \beta*x_{i} +
e_{ij}\]</span> <span class="math display">\[\hat{\alpha} =
2.13\]</span> <span class="math display">\[\hat{\beta} =
4.22\]</span></p>
<div id="character-variable" class="section level3">
<h3>character variable</h3>
<pre class="r"><code>group=rep(c(&quot;female&quot;,&quot;male&quot;), each=3)
response=rnorm (n=6, mean=0, sd=2)
data.frame(group,response)</code></pre>
<pre><code>##    group   response
## 1 female -1.6409368
## 2 female  0.9748581
## 3 female  1.4766494
## 4   male  1.1515627
## 5   male -0.6107768
## 6   male  3.0235623</code></pre>
</div>
<div id="replicate" class="section level3">
<h3>replicate()</h3>
<pre class="r"><code>replicate(n = 3, 
          expr = rnorm(n = 5, mean = 0, sd = 1),
          simplify=FALSE) # list output </code></pre>
<pre><code>## [[1]]
## [1]  0.38984324 -0.62124058 -2.21469989  1.12493092 -0.04493361
## 
## [[2]]
## [1] -0.01619026  0.94383621  0.82122120  0.59390132  0.91897737
## 
## [[3]]
## [1]  0.78213630  0.07456498 -1.98935170  0.61982575 -0.05612874</code></pre>
<pre class="r"><code>replicate(n = 3, 
          expr = rnorm(n = 5, mean = 0, sd = 1),
          )</code></pre>
<pre><code>##            [,1]        [,2]       [,3]
## [1,] -0.1557955 -0.10278773 -0.3942900
## [2,] -1.4707524  0.38767161 -0.0593134
## [3,] -0.4781501 -0.05380504  1.1000254
## [4,]  0.4179416 -1.37705956  0.7631757
## [5,]  1.3586796 -0.41499456 -0.1645236</code></pre>
<div id="loop" class="section level4">
<h4>loop</h4>
<pre class="r"><code>list1=list() # empty list to save output in. 
for(i in 1:3){
  list1[[i]]=rnorm(n=10,mean=0,sd=1)
}

print(list1)</code></pre>
<pre><code>## [[1]]
##  [1] -0.2533617  0.6969634  0.5566632 -0.6887557 -0.7074952  0.3645820
##  [7]  0.7685329 -0.1123462  0.8811077  0.3981059
## 
## [[2]]
##  [1] -0.6120264  0.3411197 -1.1293631  1.4330237  1.9803999 -0.3672215
##  [7] -1.0441346  0.5697196 -0.1350546  2.4016178
## 
## [[3]]
##  [1] -0.03924000  0.68973936  0.02800216 -0.74327321  0.18879230 -1.80495863
##  [7]  1.46555486  0.15325334  2.17261167  0.47550953</code></pre>
</div>
</div>
<div id="multiple-regression" class="section level3">
<h3>multiple regression</h3>
<pre class="r"><code>set.seed(99)

x1=rnorm(100,50,9)

x2=rbinom(100,1,0.5)
# 
# x2&lt;-ifelse(x2==0,&quot;male&quot;,&quot;female&quot;)
# x2&lt;-as.factor(x2)

error&lt;-rnorm(100,0,10)

# generating DV

y=3*x1+2*x2+error

# creating model

model1&lt;-lm(y~x1+x2)
summary(model1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = y ~ x1 + x2)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -20.379  -7.459  -2.374   7.819  25.333 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -13.0851     6.7661  -1.934    0.056 .  
## x1            3.2763     0.1396  23.475   &lt;2e-16 ***
## x2           -0.3185     2.2628  -0.141    0.888    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 10.96 on 97 degrees of freedom
## Multiple R-squared:  0.8566, Adjusted R-squared:  0.8536 
## F-statistic: 289.7 on 2 and 97 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>autoplot(model1)</code></pre>
<p><img src="p07_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
</div>
</div>
<div id="bivariate-normal" class="section level2">
<h2>Bivariate normal</h2>
<pre class="r"><code>library(MASS)

biv&lt;-mvrnorm(100, # sample size
            mu=c(0,0), # Mu
            Sigma = matrix(c(1,0.5,1,0.5),2)) # Covariance matrix

print(head(biv,10))</code></pre>
<pre><code>##              [,1]        [,2]
##  [1,]  0.21740062  0.24372187
##  [2,]  0.02515622  0.20612317
##  [3,]  1.07547205  0.24195126
##  [4,] -0.81302102  0.51264117
##  [5,] -1.60905658  0.12691964
##  [6,] -0.95313899 -0.23739452
##  [7,]  0.95274257 -0.01162121
##  [8,] -1.04822280 -0.76743874
##  [9,]  0.10481322  0.28984139
## [10,] -0.58520007  0.30456387</code></pre>
<p>visualization</p>
<pre class="r"><code># kernel density estimation 
# TMI: Yoo Ri currently did not learn what kernel density is. 

biv.kd&lt;-kde2d(biv[,1], biv[,2], n=50)
image(biv.kd)
contour(biv.kd, add=TRUE)</code></pre>
<p><img src="p07_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
</div>
<div id="multivariate-normal-simulation" class="section level2">
<h2>Multivariate Normal Simulation</h2>
<p>Generating multivariate normal data</p>
<pre class="r"><code>library(MASS)

#creating random multivariate data that has
# sample size of 50, mean of 0.5,0,10, and covariance matrix is as sigma

mul1 &lt;- MASS::mvrnorm(n = 50,       
                 mu = c(0.5, 0, 10),
                 Sigma = matrix(c(1, 0.2, 0.3,
                                  0.2, 1, 0.6,
                                  0.3, 0.6, 1),
                                nrow = 3))

print(mul1)</code></pre>
<pre><code>##               [,1]        [,2]      [,3]
##  [1,]  1.028299043  0.49299851 10.306684
##  [2,]  1.946340024  0.15977911 10.998447
##  [3,]  0.608743665 -1.67404915  6.689916
##  [4,]  0.818315919  0.06978077 10.235603
##  [5,] -2.397582590 -0.99912989  8.333358
##  [6,] -1.596951030 -1.17963925  8.774990
##  [7,] -0.989204961 -1.10363402  8.850178
##  [8,]  2.023453487 -0.60080533  9.945701
##  [9,] -0.852170244  0.12715146  9.702176
## [10,] -1.281551435  0.49792847 10.450958
## [11,]  0.769031762  0.60766349 10.956243
## [12,]  0.881271205  0.91791273  9.040802
## [13,]  1.532740759  2.36060063 12.172929
## [14,] -0.292140750  1.10946862 10.626114
## [15,] -0.100779895  0.32792726 11.240953
## [16,]  0.782663696 -0.63016137  7.929375
## [17,]  1.310126901 -0.16127999  9.545960
## [18,]  1.160138978  2.22832949 11.896473
## [19,]  1.233812290  0.13125300  9.834839
## [20,]  0.715461118 -0.15254027 10.785711
## [21,] -0.869761297 -1.73670693  8.789623
## [22,]  1.561214272  0.01860108  9.619598
## [23,]  0.766899923  0.04115885 10.555786
## [24,] -1.126940924 -1.15233962  8.621999
## [25,] -0.457199108 -0.76613387  9.855323
## [26,] -0.206186483  0.08998015 10.104040
## [27,] -0.039259876  0.54117013 10.942650
## [28,]  0.188073317  1.09005066 10.512192
## [29,]  1.418281851  0.49087103 10.771813
## [30,]  1.905544913  0.25742178 11.631258
## [31,]  0.977850805  0.64450459  9.940411
## [32,] -0.004213827 -0.82523577 10.747830
## [33,]  1.303631527  1.06001846 10.737239
## [34,]  0.335078221 -1.63231446  8.554735
## [35,] -1.049470896 -0.77738514  9.958422
## [36,]  1.220990492  1.34034713  9.576383
## [37,]  1.289822360  0.37179346 10.255645
## [38,]  0.313808888  1.19364943 10.795765
## [39,]  0.584940726 -0.06476239 10.750845
## [40,]  1.561916207  0.03496650  9.704711
## [41,]  1.165115638  0.20110712  9.239709
## [42,]  1.230384261 -0.69448991  7.851893
## [43,]  0.068486407 -0.17048247  8.732160
## [44,] -0.375259154  0.13316890  8.915430
## [45,] -1.202786713  0.83105915  9.834918
## [46,] -0.109808854 -0.14893203  9.987075
## [47,]  1.151659037  1.11174162 10.480434
## [48,]  0.406165449 -0.10188474 10.032519
## [49,]  0.175419555  0.15733456 11.540861
## [50,]  2.532515506 -0.60505926  9.113866</code></pre>
<p>Correlation matrix</p>
<pre class="r"><code>cor(mul1)</code></pre>
<pre><code>##           [,1]      [,2]      [,3]
## [1,] 1.0000000 0.3380068 0.2583901
## [2,] 0.3380068 1.0000000 0.6914499
## [3,] 0.2583901 0.6914499 1.0000000</code></pre>
<pre><code></code></pre>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
